name: .NET Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Server launcher
    strategy:
      matrix:
        kind: ['linux', 'windows', 'macOS']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS
            os: macos-latest
            target: osx-x64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Inject CF API Key
        uses: datamonsters/replace-action@v2
        with:
          replacements: '$REPLACEME$=$FOOLEDYOU$'
          files: ./CurseForge.Minecraft.Serverpack.Launcher/Program.cs

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build
        shell: bash
        run: |
          dotnet publish CurseForge.Minecraft.Serverpack.Launcher/CurseForge.Minecraft.Serverpack.Launcher.csproj --runtime "${{ matrix.target }}" -c Release -o published --self-contained
